### ISSUE TITLE
OIoooo oooo ooo screenshot in your readme???

### ISSUE THREAD

**Issue by PySimpleGUI** [andrewmk/wget_gui#1]
Would ❤ to see a screenshot in your readme!

I don't know if you've seen how I explained how to do them using GitHub Issues as an image hosting solution. It's what I usually do.  It's trivial and works great!

**Comment by PySimpleGUI** [comment]
Oh!  Or use something like ShareX to make a GIF!

**Comment by andrewmk** [comment]
Done
